### ISSUE TITLE
Cant get the car from trailer!

### ISSUE THREAD

**Issue by Ffrankys** [TanguyOrtegat/esx_jb_trailer#1]
Every time when I put a car on a trailer, i cant get it off. Tried it with every trailer..

**Comment by TanguyOrtegat** [comment]
show me a video :) becasue should work, haven't got any issue, sometimes it may bug, but not all time

**Comment by XxFri3ndlyxX** [comment]
I would assume he is restarting the resource which then will result in car getting stuck on trailer.

**Comment by TanguyOrtegat** [comment]
yea that could be it 👍  well i'll close this because of not answering to his main post
