### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [TanguyOrtegat/esx_jb_trailer#3]
Adding ability to flip trailer if flip upside down.
Or to delete vehicle.
I'm trying to add delete vehicle but i am not sure how to do it.
This is what i have so far. 
```
RegisterNetEvent("esx_jb_trailer:delete_vehicle")
AddEventHandler("esx_jb_trailer:delete_vehicle", function()

		local veh = GetClosestVehicle(x, y, z, 2, 0, 127)
		
SetEntityAsMissionEntity(vehicle, true, true)
DeleteVehicle(veh)
end)```

**Comment by TanguyOrtegat** [comment]
I don't really understand what you want to do ;) you want to flip a trailer ? but if you spawn you trailer, it on it's good place isn't it ?

**Comment by XxFri3ndlyxX** [comment]
Ok let say i get into an accident  then bam my vehicle and the trailer flip over. Well then there is nothing you can do cuz not even /dv works to delete so the trailer stays flipped upside down until server restart. So a flip or delete is needed in this case.

**Comment by TanguyOrtegat** [comment]
oh yea, now i understand, but you got like a truck with trailer, so if you don't pay attention to the road, well then the player is fucked :) next time he will drive slowly

**Comment by XxFri3ndlyxX** [comment]
Yes hence why i want to add a delete trailer otherwise it will stay stuck on the road.  Meaning it will block traffic and creating kaos at that location until server restart. Clear area from vMenu wont remove it. /dv won't delete it either.

**Comment by XxFri3ndlyxX** [comment]
Anyway i will try to find how to add this to the menu. Cause i don't want a bunch of trailers everywhere on the map. It's not good for performance. People are crazy you know. It will happen often. Then they go get a new trailer then do it again because you know... They crazy.

**Comment by TanguyOrtegat** [comment]
yea /dv could not work, but if /dv does not work, use that script for deleting vehicles. it will work
https://github.com/Ykkris/koprov/tree/72511378d7f8aa143c75a6678415546a224ef860/resources/deleteveh

**Comment by XxFri3ndlyxX** [comment]
Awesome thanks! Will give this a try.
