### ISSUE TITLE
Question about adding custom trailer

### ISSUE THREAD

**Issue by XxFri3ndlyxX** [TanguyOrtegat/esx_jb_trailer#4]
So i know i can use the small trailer code as a base for the trailer but the only thing im not sure is to get the hash number from the trailer. Do you know how i would proceed? https://www.gta5-mods.com/vehicles/2010-dodge-ram-pj-gooseneck-trailer This is what i want to add.

**Comment by XxFri3ndlyxX** [comment]
Would this be what i am looking for `<strModelFlags>20220048</strModelFlags>`

**Comment by TanguyOrtegat** [comment]
i am not sure that is the model, or you can put it on your sevrer and print the model out, or check in dlc.rpf the lanuage file and there will be a en.rpf  and if you open that the model of the tuck and trailer will me displayed

**Comment by XxFri3ndlyxX** [comment]
Okay cool thanks for answer. REally appreciate it.

**Comment by XxFri3ndlyxX** [comment]
All good got it working. There was a resource call HashGrabber so i did not had to create that to get the hash. Will send pr whenever im done with it.
